# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GGTinterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget
import pyqtgraph as pg
from pyqtgraph.opengl import GLViewWidget, GLGridItem, GLLinePlotItem, GLScatterPlotItem
import numpy as np
import pyqtgraph.opengl as gl
from open3d import geometry
from pyqtgraph.Qt import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1320, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1320, 900))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/ggtLogo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("#ggtFrame{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(10, 13, 15, 255), stop:1 rgba(71, 91, 83, 255));\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.ggtFrame = QtWidgets.QFrame(self.centralwidget)
        self.ggtFrame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(10, 13, 15, 255), stop:1 rgba(71, 91, 83, 255));\n"
"")
        self.ggtFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ggtFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ggtFrame.setObjectName("ggtFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ggtFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftColumn = QtWidgets.QWidget(self.ggtFrame)
        self.leftColumn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leftColumn.setStyleSheet("background-color: rgb(50, 66, 63);\n"
"opacity: 50%;\n"
"border: 3px solid #3BFCCC;\n"
"border-radius: 40px;\n"
"\n"
"border-top-left-radius: 60px;\n"
"border-bottom-left-radius: 60px;")
        self.leftColumn.setObjectName("leftColumn")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftColumn)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.leftwidget = QtWidgets.QWidget(self.leftColumn)
        self.leftwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leftwidget.setObjectName("leftwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftwidget)
        self.verticalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ggtBg = QtWidgets.QWidget(self.leftwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ggtBg.sizePolicy().hasHeightForWidth())
        self.ggtBg.setSizePolicy(sizePolicy)
        self.ggtBg.setMaximumSize(QtCore.QSize(16777215, 70))
        self.ggtBg.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ggtBg.setStyleSheet("border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"border-top-right-radius: 40px;\n"
"border-top-left-radius: 60px;\n"
"border: 0px;\n"
"background-color: rgb(0, 33, 25);")
        self.ggtBg.setObjectName("ggtBg")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.ggtBg)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ggtText = QtWidgets.QLabel(self.ggtBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ggtText.sizePolicy().hasHeightForWidth())
        self.ggtText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.ggtText.setFont(font)
        self.ggtText.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.ggtText.setLineWidth(1)
        self.ggtText.setAlignment(QtCore.Qt.AlignCenter)
        self.ggtText.setObjectName("ggtText")
        self.verticalLayout_3.addWidget(self.ggtText)
        self.verticalLayout_2.addWidget(self.ggtBg)
        self.ggtLogoBg = QtWidgets.QWidget(self.leftwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ggtLogoBg.sizePolicy().hasHeightForWidth())
        self.ggtLogoBg.setSizePolicy(sizePolicy)
        self.ggtLogoBg.setStyleSheet("border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"border-top-right-radius: 0px;\n"
"border-top-left-radius: 0px;\n"
"border: 0px;\n"
"\n"
"background-color: rgb(5, 86, 81);\n"
"border-radius: 0px;")
        self.ggtLogoBg.setLocale(QtCore.QLocale(QtCore.QLocale.Azerbaijani, QtCore.QLocale.Azerbaijan))
        self.ggtLogoBg.setObjectName("ggtLogoBg")
        self.formLayout = QtWidgets.QFormLayout(self.ggtLogoBg)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setObjectName("formLayout")
        self.ggtLogo = QtWidgets.QLabel(self.ggtLogoBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.ggtLogo.sizePolicy().hasHeightForWidth())
        self.ggtLogo.setSizePolicy(sizePolicy)
        self.ggtLogo.setMinimumSize(QtCore.QSize(100, 100))
        self.ggtLogo.setMaximumSize(QtCore.QSize(250, 16777215))
        self.ggtLogo.setLineWidth(13)
        self.ggtLogo.setMidLineWidth(15)
        self.ggtLogo.setText("")
        self.ggtLogo.setTextFormat(QtCore.Qt.RichText)
        self.ggtLogo.setPixmap(QtGui.QPixmap(":/logo/ggtwhite.png"))
        self.ggtLogo.setScaledContents(True)
        self.ggtLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.ggtLogo.setWordWrap(True)
        self.ggtLogo.setIndent(-16)
        self.ggtLogo.setObjectName("ggtLogo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.ggtLogo)
        self.verticalLayout_2.addWidget(self.ggtLogoBg)
        self.speedBg = QtWidgets.QWidget(self.leftwidget)
        self.speedBg.setStyleSheet("border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"border-top-right-radius: 0px;\n"
"border-top-left-radius: 0px;\n"
"border: 0px;")
        self.speedBg.setObjectName("speedBg")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.speedBg)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.speedScreen = QtWidgets.QWidget(self.speedBg)
        self.speedScreen.setObjectName("speedScreen")
        self.verticalLayout_6.addWidget(self.speedScreen)
        self.speedTextBg = QtWidgets.QWidget(self.speedBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speedTextBg.sizePolicy().hasHeightForWidth())
        self.speedTextBg.setSizePolicy(sizePolicy)
        self.speedTextBg.setMaximumSize(QtCore.QSize(16777215, 35))
        self.speedTextBg.setObjectName("speedTextBg")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.speedTextBg)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.speedConst = QtWidgets.QLabel(self.speedTextBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speedConst.sizePolicy().hasHeightForWidth())
        self.speedConst.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.speedConst.setFont(font)
        self.speedConst.setStyleSheet("color: rgb(255, 255, 255);")
        self.speedConst.setFrameShape(QtWidgets.QFrame.HLine)
        self.speedConst.setFrameShadow(QtWidgets.QFrame.Plain)
        self.speedConst.setLineWidth(16)
        self.speedConst.setMidLineWidth(15)
        self.speedConst.setTextFormat(QtCore.Qt.RichText)
        self.speedConst.setScaledContents(True)
        self.speedConst.setWordWrap(False)
        self.speedConst.setObjectName("speedConst")
        self.horizontalLayout_4.addWidget(self.speedConst)
        self.speedInput = QtWidgets.QLabel(self.speedTextBg)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.speedInput.setFont(font)
        self.speedInput.setStyleSheet("color: rgb(255, 255, 255);")
        self.speedInput.setObjectName("speedInput")
        self.horizontalLayout_4.addWidget(self.speedInput)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 2)
        self.verticalLayout_6.addWidget(self.speedTextBg)
        self.verticalLayout_2.addWidget(self.speedBg)
        self.heightBg = QtWidgets.QWidget(self.leftwidget)
        self.heightBg.setStyleSheet("border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"border-top-right-radius: 0px;\n"
"border-top-left-radius: 0px;\n"
"border: 0px;")
        self.heightBg.setObjectName("heightBg")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.heightBg)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.heightScreen = QtWidgets.QWidget(self.heightBg)
        self.heightScreen.setObjectName("heightScreen")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.heightScreen)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_11 = QtWidgets.QWidget(self.heightScreen)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_8.addWidget(self.widget_11)
        self.verticalLayout_5.addWidget(self.heightScreen)
        self.heightTextBg = QtWidgets.QWidget(self.heightBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightTextBg.sizePolicy().hasHeightForWidth())
        self.heightTextBg.setSizePolicy(sizePolicy)
        self.heightTextBg.setMaximumSize(QtCore.QSize(16777215, 35))
        self.heightTextBg.setObjectName("heightTextBg")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.heightTextBg)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.heightConst = QtWidgets.QLabel(self.heightTextBg)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.heightConst.setFont(font)
        self.heightConst.setStyleSheet("color: rgb(255, 255, 255);")
        self.heightConst.setObjectName("heightConst")
        self.horizontalLayout_3.addWidget(self.heightConst)
        self.heightInput = QtWidgets.QLabel(self.heightTextBg)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.heightInput.setFont(font)
        self.heightInput.setStyleSheet("color: rgb(255, 255, 255);")
        self.heightInput.setObjectName("heightInput")
        self.horizontalLayout_3.addWidget(self.heightInput)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.verticalLayout_5.addWidget(self.heightTextBg)
        self.verticalLayout_2.addWidget(self.heightBg)
        self.portBg = QtWidgets.QWidget(self.leftwidget)
        self.portBg.setStyleSheet("border-bottom-right-radius: 40px;\n"
"border-bottom-left-radius: 60px;\n"
"border-top-right-radius: 0px;\n"
"border-top-left-radius: 0px;\n"
"border: 0px;\n"
"background-color: rgb(5, 86, 81);")
        self.portBg.setObjectName("portBg")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.portBg)
        self.verticalLayout_4.setContentsMargins(20, 15, 20, 15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.portText = QtWidgets.QLabel(self.portBg)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.portText.setFont(font)
        self.portText.setStyleSheet("color: rgb(255, 255, 255);")
        self.portText.setObjectName("portText")
        self.verticalLayout_4.addWidget(self.portText)
        self.portInput = QtWidgets.QComboBox(self.portBg)
        self.portInput.setStyleSheet("background-color: white;\n"
"color: black;")
        self.portInput.setObjectName("portInput")
        self.verticalLayout_4.addWidget(self.portInput)
        self.baudrateText = QtWidgets.QLabel(self.portBg)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.baudrateText.setFont(font)
        self.baudrateText.setStyleSheet("color: rgb(255, 255, 255);")
        self.baudrateText.setObjectName("baudrateText")
        self.verticalLayout_4.addWidget(self.baudrateText)
        self.baudrateInput = QtWidgets.QComboBox(self.portBg)
        self.baudrateInput.setStyleSheet("background-color: white;\n"
"color: black;")
        self.baudrateInput.setObjectName("baudrateInput")
        self.verticalLayout_4.addWidget(self.baudrateInput)
        self.ipText = QtWidgets.QLabel(self.portBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ipText.sizePolicy().hasHeightForWidth())
        self.ipText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ipText.setFont(font)
        self.ipText.setStyleSheet("color: rgb(255, 255, 255);")
        self.ipText.setObjectName("ipText")
        self.verticalLayout_4.addWidget(self.ipText)
        self.ipInput = QtWidgets.QLineEdit(self.portBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ipInput.sizePolicy().hasHeightForWidth())
        self.ipInput.setSizePolicy(sizePolicy)
        self.ipInput.setStyleSheet("background-color: white;\n"
"color: black;")
        self.ipInput.setObjectName("ipInput")
        self.verticalLayout_4.addWidget(self.ipInput)
        self.ipTextEmpty = QtWidgets.QLabel(self.portBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ipTextEmpty.sizePolicy().hasHeightForWidth())
        self.ipTextEmpty.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ipTextEmpty.setFont(font)
        self.ipTextEmpty.setStyleSheet("color: rgb(255, 255, 255);")
        self.ipTextEmpty.setText("")
        self.ipTextEmpty.setObjectName("ipTextEmpty")
        self.verticalLayout_4.addWidget(self.ipTextEmpty)
        self.verticalLayout_2.addWidget(self.portBg)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 2)
        self.verticalLayout_2.setStretch(2, 2)
        self.verticalLayout_2.setStretch(3, 3)
        self.verticalLayout_2.setStretch(4, 2)
        self.verticalLayout.addWidget(self.leftwidget)
        self.horizontalLayout.addWidget(self.leftColumn)
        self.centerColumn = QtWidgets.QWidget(self.ggtFrame)
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(20)
        self.centerColumn.setFont(font)
        self.centerColumn.setStyleSheet("background-color: rgb(50, 66, 63);\n"
"opacity: 50%;\n"
"border: 3px solid #3BFCCC;\n"
"border-radius: 40px;\n"
"\n"
"")
        self.centerColumn.setObjectName("centerColumn")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.centerColumn)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.chartBg = QtWidgets.QWidget(self.centerColumn)
        self.chartBg.setStyleSheet("border: 0px;")
        self.chartBg.setObjectName("chartBg")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.chartBg)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cameraBgg = QtWidgets.QWidget(self.chartBg)
        self.cameraBgg.setObjectName("cameraBgg")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.cameraBgg)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.cameraBg = QtWidgets.QWidget(self.cameraBgg)
        self.cameraBg.setStyleSheet("border-radius: 25px;")
        self.cameraBg.setObjectName("cameraBg")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.cameraBg)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.cameraText = QtWidgets.QLabel(self.cameraBg)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(18)
        self.cameraText.setFont(font)
        self.cameraText.setStyleSheet("border: 0px;\n"
"background-color: #055651;\n"
"border-bottom-left-radius: 0 px;\n"
"border-bottom-right-radius: 0 px;\n"
"color: rgb(255, 255, 255);\n"
"padding-left: 10 px;")
        self.cameraText.setObjectName("cameraText")
        self.verticalLayout_13.addWidget(self.cameraText)
        self.cameraScreen = QtWidgets.QWidget(self.cameraBg)
        self.cameraScreen.setStyleSheet("border: 0px;\n"
"background-color: rgb(10, 40, 35);\n"
"border-top-left-radius: 0 px;\n"
"border-top-right-radius: 0 px;")
        self.cameraScreen.setObjectName("cameraScreen")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.cameraScreen)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.cameraInput = QtWidgets.QWidget(self.cameraScreen)
        self.cameraInput.setObjectName("cameraInput")
        self.verticalLayout_22.addWidget(self.cameraInput)
        self.verticalLayout_13.addWidget(self.cameraScreen)
        self.verticalLayout_13.setStretch(0, 1)
        self.verticalLayout_13.setStretch(1, 4)
        self.verticalLayout_14.addWidget(self.cameraBg)
        self.gridLayout_3.addWidget(self.cameraBgg, 1, 2, 2, 1)
        self.terminalBg = QtWidgets.QWidget(self.chartBg)
        self.terminalBg.setStyleSheet("border-radius: 25px;")
        self.terminalBg.setObjectName("terminalBg")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.terminalBg)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.terminalText = QtWidgets.QLabel(self.terminalBg)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(18)
        self.terminalText.setFont(font)
        self.terminalText.setStyleSheet("border: 0px;\n"
"background-color: #055651;\n"
"border-bottom-left-radius: 0 px;\n"
"border-bottom-right-radius: 0 px;\n"
"color: rgb(255, 255, 255);\n"
"padding-left: 10 px;")
        self.terminalText.setObjectName("terminalText")
        self.verticalLayout_9.addWidget(self.terminalText)
        self.terminalScreen = QtWidgets.QWidget(self.terminalBg)
        self.terminalScreen.setStyleSheet("border: 0px;\n"
"background-color: rgb(10, 40, 35);\n"
"border-top-left-radius: 0 px;\n"
"border-top-right-radius: 0 px;")
        self.terminalScreen.setObjectName("terminalScreen")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.terminalScreen)
        self.gridLayout_7.setContentsMargins(7, 5, 7, 5)
        self.gridLayout_7.setVerticalSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.terminalBrowser = QtWidgets.QTextBrowser(self.terminalScreen)
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(15)
        self.terminalBrowser.setFont(font)
        self.terminalBrowser.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"border-top-right-radius: 10px;\n"
"border-top-left-radius: 10px;")
        self.terminalBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.terminalBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.terminalBrowser.setObjectName("terminalBrowser")
        self.gridLayout_7.addWidget(self.terminalBrowser, 0, 0, 1, 2)
        self.terminalTextInput = QtWidgets.QLineEdit(self.terminalScreen)
        self.terminalTextInput.setStyleSheet("background-color: rgb(5, 86, 81);\n"
"padding: 3px;\n"
"padding-left: 7px;\n"
"color: rgb(255, 255, 255);\n"
"border-bottom-right-radius: 15px;\n"
"border-bottom-left-radius: 15px;\n"
"border-top-right-radius: 0px;\n"
"border-top-left-radius: 0px;\n"
"margin-bottom: 3px;\n"
"")
        self.terminalTextInput.setObjectName("terminalTextInput")
        self.gridLayout_7.addWidget(self.terminalTextInput, 1, 0, 1, 2)
        self.verticalLayout_9.addWidget(self.terminalScreen)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 3)
        self.gridLayout_3.addWidget(self.terminalBg, 3, 2, 1, 1)
        self.gpsBg = QtWidgets.QWidget(self.chartBg)
        self.gpsBg.setStyleSheet("border-radius: 25px;")
        self.gpsBg.setObjectName("gpsBg")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.gpsBg)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.GpsText = QtWidgets.QLabel(self.gpsBg)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(18)
        self.GpsText.setFont(font)
        self.GpsText.setStyleSheet("border: 0px;\n"
"background-color: #055651;\n"
"border-bottom-left-radius: 0 px;\n"
"border-bottom-right-radius: 0 px;\n"
"color: rgb(255, 255, 255);\n"
"padding-left: 10 px;")
        self.GpsText.setObjectName("GpsText")
        self.verticalLayout_12.addWidget(self.GpsText)
        self.gpsChartBg = QtWidgets.QWidget(self.gpsBg)
        self.gpsChartBg.setStyleSheet("border: 0px;\n"
"background-color: rgb(10, 40, 35);\n"
"border-top-left-radius: 0 px;\n"
"border-top-right-radius: 0 px;")
        self.gpsChartBg.setObjectName("gpsChartBg")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.gpsChartBg)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.gpsChart = QtWidgets.QGraphicsView(self.gpsChartBg)
        self.gpsChart.setObjectName("gpsChart")
        self.verticalLayout_20.addWidget(self.gpsChart)
        self.verticalLayout_12.addWidget(self.gpsChartBg)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(1, 3)
        self.gridLayout_3.addWidget(self.gpsBg, 0, 0, 1, 1)
        self.gyroBg = QtWidgets.QWidget(self.chartBg)
        self.gyroBg.setStyleSheet("border-radius: 25px;")
        self.gyroBg.setObjectName("gyroBg")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gyroBg)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gyroScreen = gl.GLViewWidget(self.gyroBg)
        self.gyroScreen.setStyleSheet("border: 0px;\n"
"background-color: rgb(10, 40, 35);\n"
"border-top-left-radius: 50 px;\n"
"border-top-right-radius: 50 px;\n"
"\n"
"border-bottom-right-radius: 0 px;")
        self.gyroScreen.setObjectName("gyroScreen")


        # GYRO
        self.cylinder = geometry.TriangleMesh.create_cylinder(radius=1.0, height=4.0)
        vertices = np.asarray(self.cylinder.vertices)
        faces = np.asarray(self.cylinder.triangles)
        self.colors = np.zeros((len(faces), 4))
        self.colors[:, 0] = 0.0
        self.colors[:, 1] = 1.0
        self.colors[:, 2] = 0.0 
        self.colors[::2, :] = [1.0, 1.0, 0.0, 1.0]

        self.mesh_item = gl.GLMeshItem(vertexes=vertices, faces=faces, faceColors=self.colors, drawEdges=True)

        self.gyroScreen.addItem(self.mesh_item)

        self.grid_item = gl.GLGridItem()
        self.gyroScreen.addItem(self.grid_item)

        self.x_axis = gl.GLAxisItem(glOptions='opaque')
        self.x_axis.rotate(90, 0, 1, 0)
        self.gyroScreen.addItem(self.x_axis)

        self.y_axis = gl.GLAxisItem(glOptions='opaque')
        self.gyroScreen.addItem(self.y_axis)

        self.z_axis = gl.GLAxisItem(glOptions='opaque')
        self.z_axis.rotate(90, 1, 0, 0)
        self.gyroScreen.addItem(self.z_axis)

        self.x_rotation_angle = 0
        self.y_rotation_angle = 0
        self.z_rotation_angle = 0

        self.gyroScreen.setCameraPosition(distance=8, elevation=30, azimuth=100)

        # END GYRO

        self.gridLayout_4.addWidget(self.gyroScreen, 1, 0, 1, 1)
        self.gyroText = QtWidgets.QLabel(self.gyroBg)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(18)
        self.gyroText.setFont(font)
        self.gyroText.setStyleSheet("border: 0px;\n"
"background-color: #055651;\n"
"border-bottom-left-radius: 0 px;\n"
"border-bottom-right-radius: 0 px;\n"
"color: rgb(255, 255, 255);\n"
"padding-left: 10 px;")
        self.gyroText.setObjectName("gyroText")
        self.gridLayout_4.addWidget(self.gyroText, 0, 0, 1, 2)
        self.gyroCor = QtWidgets.QWidget(self.gyroBg)
        self.gyroCor.setStyleSheet("border: 0px;\n"
"background-color: rgb(10, 40, 35);\n"
"border-top-left-radius: 0 px;\n"
"border-top-right-radius: 0 px;\n"
"border-bottom-left-radius: 0 px;\n"
"")
        self.gyroCor.setObjectName("gyroCor")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gyroCor)
        self.gridLayout_5.setContentsMargins(3, 3, 9, 3)
        self.gridLayout_5.setVerticalSpacing(3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.xText = QtWidgets.QLabel(self.gyroCor)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.xText.setFont(font)
        self.xText.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 25px;\n"
"font: 20pt \"BankGothic Lt BT\";")
        self.xText.setObjectName("xText")
        self.gridLayout_5.addWidget(self.xText, 0, 0, 1, 1)
        self.xInput = QtWidgets.QLabel(self.gyroCor)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.xInput.setFont(font)
        self.xInput.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 25px;\n"
"font: 20pt \"BankGothic Lt BT\";")
        self.xInput.setObjectName("xInput")
        self.gridLayout_5.addWidget(self.xInput, 0, 1, 1, 1)
        self.yText = QtWidgets.QLabel(self.gyroCor)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.yText.setFont(font)
        self.yText.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 25px;\n"
"font: 20pt \"BankGothic Lt BT\";")
        self.yText.setObjectName("yText")
        self.gridLayout_5.addWidget(self.yText, 1, 0, 1, 1)
        self.yInput = QtWidgets.QLabel(self.gyroCor)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.yInput.setFont(font)
        self.yInput.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 25px;\n"
"font: 20pt \"BankGothic Lt BT\";")
        self.yInput.setObjectName("yInput")
        self.gridLayout_5.addWidget(self.yInput, 1, 1, 1, 1)
        self.zText = QtWidgets.QLabel(self.gyroCor)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.zText.setFont(font)
        self.zText.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 25px;\n"
"font: 20pt \"BankGothic Lt BT\";")
        self.zText.setObjectName("zText")
        self.gridLayout_5.addWidget(self.zText, 2, 0, 1, 1)
        self.zInput = QtWidgets.QLabel(self.gyroCor)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.zInput.setFont(font)
        self.zInput.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 25px;\n"
"font: 20pt \"BankGothic Lt BT\";")
        self.zInput.setObjectName("zInput")
        self.gridLayout_5.addWidget(self.zInput, 2, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_5.setColumnStretch(1, 3)
        self.gridLayout_4.addWidget(self.gyroCor, 1, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 4)
        self.gridLayout_4.setColumnStretch(1, 3)
        self.gridLayout_4.setRowStretch(0, 1)
        self.gridLayout_4.setRowStretch(1, 3)
        self.gridLayout_3.addWidget(self.gyroBg, 0, 2, 1, 1)
        self.preaBg = QtWidgets.QWidget(self.chartBg)
        self.preaBg.setStyleSheet("border-radius: 25px;")
        self.preaBg.setObjectName("preaBg")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.preaBg)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.preaText = QtWidgets.QLabel(self.preaBg)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(18)
        self.preaText.setFont(font)
        self.preaText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.preaText.setStyleSheet("border: 0px;\n"
"background-color: #055651;\n"
"border-bottom-left-radius: 0 px;\n"
"border-bottom-right-radius: 0 px;\n"
"color: rgb(255, 255, 255);\n"
"padding-left: 10 px;\n"
"\n"
"")
        self.preaText.setObjectName("preaText")
        self.verticalLayout_15.addWidget(self.preaText)
        self.preaScreen = QtWidgets.QWidget(self.preaBg)
        self.preaScreen.setStyleSheet("border: 0px;\n"
"background-color: rgb(10, 40, 35);\n"
"border-top-left-radius: 0 px;\n"
"border-top-right-radius: 0 px;")
        self.preaScreen.setObjectName("preaScreen")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.preaScreen)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame = QtWidgets.QFrame(self.preaScreen)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_19.addWidget(self.frame)
        self.verticalLayout_15.addWidget(self.preaScreen)

        ## Prea Chart
        self.preaChart = PlotWidget(self.preaScreen, background='transparent')
        self.verticalLayout_19.addWidget(self.preaChart)
        self.preaChart.plot([])
        self.preaChart.setMouseEnabled(x=False, y=True)
        self.preaChart.setGeometry(QtCore.QRect(0, 0, 100, 100))

        #####################################################################

        self.verticalLayout_15.setStretch(0, 1)
        self.verticalLayout_15.setStretch(1, 4)
        self.gridLayout_3.addWidget(self.preaBg, 1, 0, 2, 1)
        self.tempBg = QtWidgets.QWidget(self.chartBg)
        self.tempBg.setStyleSheet("border-radius: 25px;")
        self.tempBg.setObjectName("tempBg")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tempBg)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.tempText = QtWidgets.QLabel(self.tempBg)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(18)
        self.tempText.setFont(font)
        self.tempText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tempText.setStyleSheet("border: 0px;\n"
"background-color: #055651;\n"
"border-bottom-left-radius: 0 px;\n"
"border-bottom-right-radius: 0 px;\n"
"color: rgb(255, 255, 255);\n"
"padding-left: 10 px;\n"
"")
        self.tempText.setObjectName("tempText")
        self.verticalLayout_16.addWidget(self.tempText)
        self.tempScreen = QtWidgets.QWidget(self.tempBg)
        self.tempScreen.setStyleSheet("border: 0px;\n"
"background-color: rgb(10, 40, 35);\n"
"border-top-left-radius: 0 px;\n"
"border-top-right-radius: 0 px;")
        self.tempScreen.setObjectName("tempScreen")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.tempScreen)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame2 = QtWidgets.QFrame(self.tempScreen)
        self.frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2.setObjectName("frame2")
        self.verticalLayout_21.addWidget(self.frame2)

        ## Temp Chart
        self.tempChart = PlotWidget(self.tempScreen, background='transparent')
        self.verticalLayout_21.addWidget(self.tempChart)
        self.tempChart.plot([])
        self.tempChart.setMouseEnabled(x=False, y=True)
        self.tempChart.setGeometry(QtCore.QRect(0, 0, 100, 100))
        #####################################################################

        self.verticalLayout_16.addWidget(self.tempScreen)
        self.verticalLayout_16.setStretch(0, 1)
        self.verticalLayout_16.setStretch(1, 3)
        self.gridLayout_3.addWidget(self.tempBg, 3, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 3)
        self.gridLayout_3.setColumnStretch(2, 4)
        self.gridLayout_3.setRowStretch(0, 3)
        self.gridLayout_3.setRowStretch(1, 2)
        self.gridLayout_3.setRowStretch(2, 2)
        self.gridLayout_3.setRowStretch(3, 3)
        self.verticalLayout_11.addWidget(self.chartBg)
        self.horizontalLayout.addWidget(self.centerColumn)
        self.rightColumn = QtWidgets.QWidget(self.ggtFrame)
        self.rightColumn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.rightColumn.setStyleSheet("background-color: rgb(50, 66, 63);\n"
"opacity: 50%;\n"
"border: 3px solid #3BFCCC;\n"
"border-radius: 40px;\n"
"\n"
"border-top-right-radius: 60px;\n"
"border-bottom-right-radius: 60px;\n"
"")
        self.rightColumn.setObjectName("rightColumn")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.rightColumn)
        self.verticalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.rightwidget = QtWidgets.QWidget(self.rightColumn)
        self.rightwidget.setStyleSheet("border: 0px;")
        self.rightwidget.setObjectName("rightwidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.rightwidget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.dateBg = QtWidgets.QWidget(self.rightwidget)
        self.dateBg.setMinimumSize(QtCore.QSize(0, 60))
        self.dateBg.setMaximumSize(QtCore.QSize(16777215, 60))
        self.dateBg.setStyleSheet("border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"border-top-right-radius: 60px;\n"
"border-top-left-radius: 40px;\n"
"border: 0px;\n"
"background-color: rgb(0, 33, 25);")
        self.dateBg.setObjectName("dateBg")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.dateBg)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.dateInput = QtWidgets.QLabel(self.dateBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateInput.sizePolicy().hasHeightForWidth())
        self.dateInput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.dateInput.setFont(font)
        self.dateInput.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.dateInput.setLineWidth(1)
        self.dateInput.setAlignment(QtCore.Qt.AlignCenter)
        self.dateInput.setObjectName("dateInput")
        self.verticalLayout_10.addWidget(self.dateInput)
        self.verticalLayout_8.addWidget(self.dateBg)
        self.clockBg = QtWidgets.QWidget(self.rightwidget)
        self.clockBg.setStyleSheet("background-color: rgb(5, 86, 81);\n"
"border-radius: 0px;")
        self.clockBg.setObjectName("clockBg")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.clockBg)
        self.gridLayout_2.setContentsMargins(10, 5, 10, 5)
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.clockInput = QtWidgets.QLabel(self.clockBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clockInput.sizePolicy().hasHeightForWidth())
        self.clockInput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.clockInput.setFont(font)
        self.clockInput.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.clockInput.setLineWidth(1)
        self.clockInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.clockInput.setObjectName("clockInput")
        self.gridLayout_2.addWidget(self.clockInput, 1, 1, 1, 1)
        self.startInput = QtWidgets.QLabel(self.clockBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startInput.sizePolicy().hasHeightForWidth())
        self.startInput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.startInput.setFont(font)
        self.startInput.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.startInput.setLineWidth(1)
        self.startInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.startInput.setObjectName("startInput")
        self.gridLayout_2.addWidget(self.startInput, 2, 1, 1, 1)
        self.finishText = QtWidgets.QLabel(self.clockBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.finishText.sizePolicy().hasHeightForWidth())
        self.finishText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.finishText.setFont(font)
        self.finishText.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.finishText.setLineWidth(1)
        self.finishText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.finishText.setObjectName("finishText")
        self.gridLayout_2.addWidget(self.finishText, 4, 0, 1, 1)
        self.finishInput = QtWidgets.QLabel(self.clockBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.finishInput.sizePolicy().hasHeightForWidth())
        self.finishInput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.finishInput.setFont(font)
        self.finishInput.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.finishInput.setLineWidth(1)
        self.finishInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.finishInput.setObjectName("finishInput")
        self.gridLayout_2.addWidget(self.finishInput, 4, 1, 1, 1)
        self.breakText = QtWidgets.QLabel(self.clockBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.breakText.sizePolicy().hasHeightForWidth())
        self.breakText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.breakText.setFont(font)
        self.breakText.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.breakText.setLineWidth(1)
        self.breakText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.breakText.setObjectName("breakText")
        self.gridLayout_2.addWidget(self.breakText, 3, 0, 1, 1)
        self.breakInput = QtWidgets.QLabel(self.clockBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.breakInput.sizePolicy().hasHeightForWidth())
        self.breakInput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.breakInput.setFont(font)
        self.breakInput.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.breakInput.setLineWidth(1)
        self.breakInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.breakInput.setObjectName("breakInput")
        self.gridLayout_2.addWidget(self.breakInput, 3, 1, 1, 1)
        self.startText = QtWidgets.QLabel(self.clockBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startText.sizePolicy().hasHeightForWidth())
        self.startText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.startText.setFont(font)
        self.startText.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.startText.setLineWidth(1)
        self.startText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.startText.setObjectName("startText")
        self.gridLayout_2.addWidget(self.startText, 2, 0, 1, 1)
        self.clockText = QtWidgets.QLabel(self.clockBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clockText.sizePolicy().hasHeightForWidth())
        self.clockText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.clockText.setFont(font)
        self.clockText.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.clockText.setLineWidth(1)
        self.clockText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.clockText.setObjectName("clockText")
        self.gridLayout_2.addWidget(self.clockText, 1, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.clockBg)
        self.btns = QtWidgets.QWidget(self.rightwidget)
        self.btns.setObjectName("btns")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.btns)
        self.verticalLayout_18.setContentsMargins(5, 10, 5, 10)
        self.verticalLayout_18.setSpacing(10)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.startBtn = QtWidgets.QPushButton(self.btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startBtn.sizePolicy().hasHeightForWidth())
        self.startBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.startBtn.setFont(font)
        self.startBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startBtn.setMouseTracking(False)
        self.startBtn.setAcceptDrops(False)
        self.startBtn.setStyleSheet("QPushButton {\n"
"\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 33, 25);\n"
"border-radius: 15px;\n"
"font: 24pt \"BankGothic Lt BT\";\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border: 3px solid #3BFCCC;\n"
"color: rgb(255, 255, 255);\n"
"background-color: #055651;\n"
"border-radius: 15px;\n"
"\n"
"\n"
"}")
        self.startBtn.setCheckable(False)
        self.startBtn.setFlat(False)
        self.startBtn.setProperty("color", QtGui.QColor(0, 0, 0))
        self.startBtn.setObjectName("startBtn")
        self.verticalLayout_18.addWidget(self.startBtn)
        self.gpsBtn = QtWidgets.QPushButton(self.btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gpsBtn.sizePolicy().hasHeightForWidth())
        self.gpsBtn.setSizePolicy(sizePolicy)
        self.gpsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gpsBtn.setStyleSheet("QPushButton {\n"
"\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 33, 25);\n"
"border-radius: 15px;\n"
"font: 24pt \"BankGothic Lt BT\";\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border: 3px solid #3BFCCC;\n"
"color: rgb(255, 255, 255);\n"
"background-color: #055651;\n"
"border-radius: 15px;\n"
"\n"
"}")
        self.gpsBtn.setObjectName("gpsBtn")
        self.verticalLayout_18.addWidget(self.gpsBtn)
        self.gyroBtn = QtWidgets.QPushButton(self.btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gyroBtn.sizePolicy().hasHeightForWidth())
        self.gyroBtn.setSizePolicy(sizePolicy)
        self.gyroBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gyroBtn.setStyleSheet("QPushButton{color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 33, 25);\n"
"border-radius: 15px;\n"
"font: 24pt \"BankGothic Lt BT\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 3px solid #3BFCCC;\n"
"color: rgb(255, 255, 255);\n"
"background-color: #055651;\n"
"border-radius: 15px;\n"
"\n"
"}")
        self.gyroBtn.setObjectName("gyroBtn")
        self.verticalLayout_18.addWidget(self.gyroBtn)
        self.preaBtn = QtWidgets.QPushButton(self.btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preaBtn.sizePolicy().hasHeightForWidth())
        self.preaBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.preaBtn.setFont(font)
        self.preaBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.preaBtn.setStyleSheet("QPushButton{color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 33, 25);\n"
"border-radius: 15px;\n"
"font: 24pt \"BankGothic Lt BT\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 3px solid #3BFCCC;\n"
"color: rgb(255, 255, 255);\n"
"background-color: #055651;\n"
"border-radius: 15px;\n"
"\n"
"}")
        
        self.verticalLayout_18.addWidget(self.preaBtn)
        self.tempBtn = QtWidgets.QPushButton(self.btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempBtn.sizePolicy().hasHeightForWidth())
        self.tempBtn.setSizePolicy(sizePolicy)
        self.tempBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tempBtn.setStyleSheet("QPushButton{color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 33, 25);\n"
"border-radius: 15px;\n"
"font: 24pt \"BankGothic Lt BT\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 3px solid #3BFCCC;\n"
"color: rgb(255, 255, 255);\n"
"background-color: #055651;\n"
"border-radius: 15px;\n"
"\n"
"}")
        self.tempBtn.setObjectName("tempBtn")
        self.verticalLayout_18.addWidget(self.tempBtn)
        self.verticalLayout_18.setStretch(0, 1)
        self.verticalLayout_18.setStretch(1, 1)
        self.verticalLayout_18.setStretch(2, 1)
        self.verticalLayout_18.setStretch(3, 1)
        self.verticalLayout_18.setStretch(4, 1)
        self.startBtn.raise_()
        self.gyroBtn.raise_()
        self.preaBtn.raise_()
        self.tempBtn.raise_()
        self.gpsBtn.raise_()
        self.verticalLayout_8.addWidget(self.btns)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 2)
        self.verticalLayout_8.setStretch(2, 12)
        self.verticalLayout_7.addWidget(self.rightwidget)
        self.errorsBg = QtWidgets.QWidget(self.rightColumn)
        self.errorsBg.setStyleSheet("border: 0px;")
        self.errorsBg.setObjectName("errorsBg")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.errorsBg)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.errorText = QtWidgets.QLabel(self.errorsBg)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(16)
        self.errorText.setFont(font)
        self.errorText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.errorText.setStyleSheet("border: 0px;\n"
"background-color: #055651;\n"
"border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"border-top-right-radius: 15px;\n"
"border-top-left-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"padding: 10 px;\n"
"padding-left: 5px;")
        self.errorText.setObjectName("errorText")
        self.verticalLayout_17.addWidget(self.errorText)
        self.errorScreen = QtWidgets.QWidget(self.errorsBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.errorScreen.sizePolicy().hasHeightForWidth())
        self.errorScreen.setSizePolicy(sizePolicy)
        self.errorScreen.setStyleSheet("border: 0px solid;\n"
"background-color: rgb(10, 40, 35);\n"
"\n"
"border-bottom-right-radius: 55px;\n"
"border-bottom-left-radius: 35px;\n"
"border-top-right-radius: 0px;\n"
"border-top-left-radius: 0px;")
        self.errorScreen.setObjectName("errorScreen")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.errorScreen)
        self.gridLayout_6.setContentsMargins(10, 10, 10, -1)
        self.gridLayout_6.setSpacing(10)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.error1Bg = QtWidgets.QWidget(self.errorScreen)
        self.error1Bg.setStyleSheet("border: 3px solid #3BFCCC;\n"
"border-radius: 7px;")
        self.error1Bg.setObjectName("error1Bg")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.error1Bg)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.error1Text = QtWidgets.QLabel(self.error1Bg)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(22)
        self.error1Text.setFont(font)
        self.error1Text.setStyleSheet("color: white;\n"
"background-color: #055651;\n"
"border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius: 7px;\n"
"border-top-right-radius: 0px;\n"
"border-top-left-radius: 7px;")
        self.error1Text.setAlignment(QtCore.Qt.AlignCenter)
        self.error1Text.setObjectName("error1Text")
        self.horizontalLayout_2.addWidget(self.error1Text)
        self.error1 = QtWidgets.QWidget(self.error1Bg)
        self.error1.setStyleSheet("border-bottom-right-radius: 7px;\n"
"border-bottom-left-radius: 0px;\n"
"border-top-right-radius: 7px;\n"
"background-color: rgb(255, 0, 0);\n"
"border-top-left-radius: 0px;")
        self.error1.setObjectName("error1")
        self.horizontalLayout_2.addWidget(self.error1)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 5)
        self.gridLayout_6.addWidget(self.error1Bg, 4, 0, 1, 1)
        self.error3Bg = QtWidgets.QWidget(self.errorScreen)
        self.error3Bg.setStyleSheet("border: 3px solid #3BFCCC;\n"
"border-radius: 7px;")
        self.error3Bg.setObjectName("error3Bg")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.error3Bg)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.error3Text = QtWidgets.QLabel(self.error3Bg)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(22)
        self.error3Text.setFont(font)
        self.error3Text.setStyleSheet("color: white;\n"
"background-color: #055651;\n"
"border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius: 7px;\n"
"border-top-right-radius: 0px;\n"
"border-top-left-radius: 7px;")
        self.error3Text.setAlignment(QtCore.Qt.AlignCenter)
        self.error3Text.setObjectName("error3Text")
        self.horizontalLayout_6.addWidget(self.error3Text)
        self.error3 = QtWidgets.QWidget(self.error3Bg)
        self.error3.setStyleSheet("border-bottom-right-radius: 7px;\n"
"border-bottom-left-radius: 0px;\n"
"border-top-right-radius: 7px;\n"
"border-top-left-radius: 0px;\n"
"background-color: rgb(255, 0, 0);")
        self.error3.setObjectName("error3")
        self.horizontalLayout_6.addWidget(self.error3)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 5)
        self.gridLayout_6.addWidget(self.error3Bg, 6, 0, 1, 1)
        self.error4Bg = QtWidgets.QWidget(self.errorScreen)
        self.error4Bg.setStyleSheet("border: 3px solid #3BFCCC;\n"
"border-radius: 7px;")
        self.error4Bg.setObjectName("error4Bg")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.error4Bg)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.error4Text = QtWidgets.QLabel(self.error4Bg)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(22)
        self.error4Text.setFont(font)
        self.error4Text.setStyleSheet("color: white;\n"
"background-color: #055651;\n"
"border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius: 7px;\n"
"border-top-right-radius: 0px;\n"
"border-top-left-radius: 7px;")
        self.error4Text.setAlignment(QtCore.Qt.AlignCenter)
        self.error4Text.setObjectName("error4Text")
        self.horizontalLayout_5.addWidget(self.error4Text)
        self.error4 = QtWidgets.QWidget(self.error4Bg)
        self.error4.setStyleSheet("border-bottom-right-radius: 7px;\n"
"border-bottom-left-radius: 0px;\n"
"border-top-right-radius: 7px;\n"
"border-top-left-radius: 0px;\n"
"background-color: rgb(0, 155, 0);")
        self.error4.setObjectName("error4")
        self.horizontalLayout_5.addWidget(self.error4)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 5)
        self.gridLayout_6.addWidget(self.error4Bg, 7, 0, 1, 1)
        self.bosluq = QtWidgets.QWidget(self.errorScreen)
        self.bosluq.setMinimumSize(QtCore.QSize(0, 20))
        self.bosluq.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.bosluq.setObjectName("bosluq")
        self.gridLayout_6.addWidget(self.bosluq, 8, 0, 1, 1)
        self.error2Bg = QtWidgets.QWidget(self.errorScreen)
        self.error2Bg.setStyleSheet("border: 3px solid #3BFCCC;\n"
"border-radius: 7px;")
        self.error2Bg.setObjectName("error2Bg")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.error2Bg)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.error2Text = QtWidgets.QLabel(self.error2Bg)
        font = QtGui.QFont()
        font.setFamily("BankGothic Lt BT")
        font.setPointSize(22)
        self.error2Text.setFont(font)
        self.error2Text.setStyleSheet("color: white;\n"
"background-color: #055651;\n"
"border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius: 7px;\n"
"border-top-right-radius: 0px;\n"
"border-top-left-radius: 7px;")
        self.error2Text.setAlignment(QtCore.Qt.AlignCenter)
        self.error2Text.setObjectName("error2Text")
        self.horizontalLayout_7.addWidget(self.error2Text)
        self.error2 = QtWidgets.QWidget(self.error2Bg)
        self.error2.setStyleSheet("border-bottom-right-radius: 7px;\n"
"border-bottom-left-radius: 0px;\n"
"border-top-right-radius: 7px;\n"
"border-top-left-radius: 0px;\n"
"background-color: rgb(0, 155, 0);")
        self.error2.setObjectName("error2")
        self.horizontalLayout_7.addWidget(self.error2)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 5)
        self.gridLayout_6.addWidget(self.error2Bg, 5, 0, 1, 1)
        self.verticalLayout_17.addWidget(self.errorScreen)
        self.verticalLayout_17.setStretch(0, 1)
        self.verticalLayout_17.setStretch(1, 2)
        self.verticalLayout_7.addWidget(self.errorsBg)
        self.verticalLayout_7.setStretch(0, 5)
        self.verticalLayout_7.setStretch(1, 2)
        self.horizontalLayout.addWidget(self.rightColumn)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 1)
        self.gridLayout.addWidget(self.ggtFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ggtText.setText(_translate("MainWindow", "GARGANTUA"))
        self.speedConst.setText(_translate("MainWindow", "speed:"))
        self.speedInput.setText(_translate("MainWindow", "6 m/s"))
        self.heightConst.setText(_translate("MainWindow", "height:"))
        self.heightInput.setText(_translate("MainWindow", "220 m"))
        self.portText.setText(_translate("MainWindow", "PORT:"))
        self.baudrateText.setText(_translate("MainWindow", "BAUD RATE:"))
        self.ipText.setText(_translate("MainWindow", "CAMERA IP:"))
        self.cameraText.setText(_translate("MainWindow", "CAMERA"))
        self.terminalText.setText(_translate("MainWindow", "TERMINAL"))
        self.terminalBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Terminal\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#f3ff00;\"> connecting..</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#00ff00;\"> connected</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#00ff00;\">  </span><span style=\" font-size:8pt; color:#ffffff;\">Mpu9250:</span><span style=\" font-size:8pt; color:#00ff00;\"> succes</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#00ff00;\">  </span><span style=\" font-size:8pt; color:#ffffff;\">Ms5611:</span><span style=\" font-size:8pt; color:#00ff00;\"> succes</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#00ff00;\">  </span><span style=\" font-size:8pt; color:#ffffff;\">Neo-6m:</span><span style=\" font-size:8pt; color:#00ff00;\"> succes</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#00ff00;\">  </span><span style=\" font-size:8pt; color:#ffffff;\">Ov2735:</span><span style=\" font-size:8pt; color:#00ff00;\"> succes</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#00ff00;\">  </span><span style=\" font-size:8pt; color:#ffffff;\">Xbee Pro S2C:</span><span style=\" font-size:8pt; color:#00ff00;\"> succes</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; color:#00ff00;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; color:#ffffff;\">  .reset</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#22ff00;\"> resetted</span></p></body></html>"))
        self.terminalTextInput.setText(_translate("MainWindow", "text"))
        self.GpsText.setText(_translate("MainWindow", "GPS"))
        self.gyroText.setText(_translate("MainWindow", "GYRO"))
        self.xText.setText(_translate("MainWindow", " X AXIS:"))
        self.xInput.setText(_translate("MainWindow", "0"))
        self.yText.setText(_translate("MainWindow", " Y AXIS:"))
        self.yInput.setText(_translate("MainWindow", "0"))
        self.zText.setText(_translate("MainWindow", " Z AXIS:"))
        self.zInput.setText(_translate("MainWindow", "0"))
        self.preaText.setText(_translate("MainWindow", "PREASURE"))
        self.tempText.setText(_translate("MainWindow", "TEMPERATURE"))
        self.dateInput.setText(_translate("MainWindow", "DATE"))
        self.clockInput.setText(_translate("MainWindow", "16:50"))
        self.startInput.setText(_translate("MainWindow", "16:00"))
        self.finishText.setText(_translate("MainWindow", "finish:"))
        self.finishInput.setText(_translate("MainWindow", "17:00"))
        self.breakText.setText(_translate("MainWindow", "break:"))
        self.breakInput.setText(_translate("MainWindow", "16:25"))
        self.startText.setText(_translate("MainWindow", "start:"))
        self.clockText.setText(_translate("MainWindow", "clock:"))
        self.startBtn.setText(_translate("MainWindow", "START"))
        self.gpsBtn.setText(_translate("MainWindow", "GPS"))
        self.gyroBtn.setText(_translate("MainWindow", "GYRO"))
        self.preaBtn.setText(_translate("MainWindow", "PREASURE"))
        self.tempBtn.setText(_translate("MainWindow", "temperature"))
        self.errorText.setText(_translate("MainWindow", "ERRORs"))
        self.error1Text.setText(_translate("MainWindow", "1"))
        self.error3Text.setText(_translate("MainWindow", "3"))
        self.error4Text.setText(_translate("MainWindow", "4"))
        self.error2Text.setText(_translate("MainWindow", "2"))


import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
